### ISSUE TITLE
Installation issues of JDK on low version Burp

### ISSUE THREAD

**Issue by carpenter-l** [DolphFlynn/jwt-editor#63]
When using the version of Burp 2022, it cannot be installed in BAPP storez. Will we consider providing lower version plugins in the future?
![image](https://github.com/user-attachments/assets/766016d0-0904-48fc-92d1-4b81d6c85d30)

**Comment by DolphFlynn** [comment]
In terms of the BApp Store, you will need to ask PortSwigger. As far as I know, they only support the latest version of each BApp, but if you contact them, they can assist you.

With respect to running JWT Editor on old versions of Burp, in general, it will work as long as you avoid method calls that have been implemented in more recent versions. However 2022 versions are probably still using the old _IBurpExtender_ API so your best bet is to check out and build the original [BlackBerry version](https://github.com/blackberry/jwt-editor). If you need help building it then let me know.

How come you're using such an old version of Burp?

**Comment by carpenter-l** [comment]
Hello, the reason for using the old version of Burp is that the new version of Burp is not as convenient in terms of UI and usage as the old version. Perhaps there are still many people using old versions of Burp for various reasons such as nostalgia. If you could compile the JWT plugin for the old version of Burp, I would greatly appreciate it

**Comment by DolphFlynn** [comment]
It's been a while since I worked with the BlackBerry version, but these steps should work for you:

* Ensure that Java JDK 17 or newer is installed 
* Install [Apache Maven](https://maven.apache.org/) 
* Clone the [BlackBerry repository](https://github.com/blackberry/jwt-editor)
* From the root of project, run the command `mvn package`

This should put the file _jwt-editor-1.1.0-jar-with-dependencies.jar_ into the _target_ diretory which you can then load into Burp.
